services:
  backend:
    restart: always
    build:
      context: ./backend/pybooking
      dockerfile: Dockerfile.backend
      args:
        CONFIGURATION: "debug"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/pybooking:/app # Mount the source code for development
    env_file:
      - ./backend/pybooking/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/utils/health-check"]
      interval: 60s
      timeout: 5s
      retries: 5

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        CONFIGURATION: "debug"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env
volumes:
  frontend_node_modules:
